### ISSUE TITLE
Avaliar objetivo da tela Home

### ISSUE THREAD

**Issue by hosanabarcelos** [ZenilsonJunior/telas#1]
Não entendi qual seria o objetivo da Home para pensar numa implementação adequada... Qual seria o conteúdo? Dashboard? Quem vai ter acesso a essa rota? Existe alguma outra view associada a ela?

**Comment by hosanabarcelos** [comment]
Alguma atualização? Como ficou definido de como será a tela Início?

**Comment by ZenilsonJunior** [comment]
[image: image.png]
Estava pensando em colocar ela assim.

Em seg., 31 de out. de 2022 às 15:55, Hosana Barcelos <
***@***.***> escreveu:
