### ISSUE TITLE
Avaliar fonte padrão para as views

### ISSUE THREAD

**Issue by hosanabarcelos** [ZenilsonJunior/telas#3]
É interessante definir uma fonte padrão para todas as telas. [Google Fonts](https://fonts.google.com/) é uma boa e bem simples!

**Comment by ZenilsonJunior** [comment]
font  Raleway, enviei a tela home vou tentar terminar as outras tudo hoje.

Em qua., 26 de out. de 2022 às 13:00, Hosana Barcelos <
***@***.***> escreveu:
